# This is a config for E2B sandbox template.
# You can use template ID (1tomir50oef7c193swv1) or template name (vibe-testing2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-testing2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-testing2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-testing2')

team_id = "bad9975d-46cd-4bd5-97d4-fbdbca8e36a2"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-testing2"
template_id = "1tomir50oef7c193swv1"
